name: Build and Release UWP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore EldenTracker.sln

      - name: Build the project
        run: msbuild EldenTracker.sln /p:Configuration=Release

      - name: Create output directory
        run: mkdir build

      - name: Copy build artifacts
        run: |
          copy EldenTracker\bin\Release\net5.0-windows\* build\
          dir build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: elden-tracker-build
          path: build
